- block:
  - name: aur | user > check aur user exists
    user:
      name:  aur
      state: present

  - include_tasks: "{{ aur_helper }}.yml"
  # - yay
  # - aura-bin

  when: aur_helper
  tags: aur
