- block:
  - import_tasks: pacman.yml

  - import_tasks: reflector.yml

  - import_tasks: aur.yml

  - import_tasks: upgrade.yml

  - import_tasks: makepkg.yml

  # - import_tasks: hooks.yml   ## TODO

  - import_tasks: paccache.yml

  - import_tasks: auto_update.yml

  when: ansible_distribution in ["Archlinux","Artix Linux"]
  become_user: root
  tags: pacman
