- block:
  - name: paru | file > create paru config dir
    file:
      path:  "/home/{{ aur_user + '/' + item }}"
      state: directory
    with_items:
      - "{{ path_config }}/paru"
      - "{{ path_cache  }}/ansible"         # because first time ansible run as aur user

  - name: paru | file > create paru cache dir for {{ aur_user }}
    file:
      path:  "/home/{{ aur_user + '/' + path_cache_aur }}"
      state: directory
      owner: "{{ aur_user }}"

  - name: paru | package > intall paru dependencies
    package:
      name: "{{ item }}"
    loop:
      - base-devel
      - rust
    become: true

  # KO, aur module not able to install on remote if paru not alread installed, compiled it instead
  # binary version
  # - name: paru | aur > install dependencies
  #   aur:
  #     name: "{{ item }}"
  #   loop:
  #     - paru-bin
  #   become_user: "{{ aur_user }}"

  # KO, makepkg -si needs a sudo password and become_user: root is not allowed
  # - name: paru | git > clone paru repository
  #   git:
  #     repo:  https://aur.archlinux.org/paru.git
  #     dest:  /tmp/paru
  # - name: paru | shell > build paru binary
  #   shell:
  #     cmd: cd /tmp/paru; makepkg -si

  - name: paru | template > generate paru config file
    template:
      src:  paru.conf
      dest: "/home/{{ aur_user + '/' + path_config }}/paru/paru.conf"

  become_user: "{{ aur_user }}"
  tags: paru
